version: "3.6"
services:
  amachiromaker:
    build: .
    image: charlie0129/amachiromaker-clone
    container_name: amachiromaker
    restart: unless-stopped
    networks:
      - traefik-global-proxy # change this to you network where traefik lives in
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.amachiromaker.rule=Host(`${WEBSITE_URL}`)"
      - "traefik.http.routers.amachiromaker.entrypoints=web"
      - "traefik.http.services.amachiromaker.loadbalancer.server.port=80"
      - "traefik.http.routers.amachiromaker.middlewares=amachiromaker-compress"
      - "traefik.http.middlewares.amachiromaker-compress.compress=true"
    environment:
      - "NODE_ENV=production"

networks:
  traefik-global-proxy: # change this to you network where traefik lives in
    external: true
