version: "3.6"
services:
  amachiromaker:
    build: .
    image: charlie0129/amachiromaker
    container_name: amachiromaker
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - traefik-global-proxy # change this to you network where traefik lives in
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.amachiromaker.entrypoints=web"
      - "traefik.http.routers.amachiromaker.rule=Host(`${WEBSITE_URL}`)"
      - "traefik.http.middlewares.amachiromaker-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.amachiromaker.middlewares=amachiromaker-https-redirect"
      - "traefik.http.routers.amachiromaker-secure.entrypoints=websecure"
      - "traefik.http.routers.amachiromaker-secure.rule=Host(`${WEBSITE_URL}`)"
      - "traefik.http.routers.amachiromaker-secure.tls=true"
    environment:
      - "NODE_ENV=production"

networks:
  traefik-global-proxy: # change this to you network where traefik lives in
    external: true
